name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  schedule:
    - cron: '0 10 * * SAT'


jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: pip install nox
      - name: Coverage
        run: nox -s coverage

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install nox
        run: pip install nox
      - name: Run flake8
        run: nox -s flake8
      - name: Run pylint
        run: nox -s pylint
      - name: Run pydocstyle
        run: nox -s pydocstyle

  docs:
    name: Build and push docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # To fetch all refs
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install nox
        run: pip install nox
      - name: Build docs
        run: nox -s docs -- -d /tmp/sphinx-doctrees
      - name: Commit and push docs
        run: |
          alias gitw="git --work-tree docs/build"
          gitw checkout gh-pages
          gitw rm -r .  # Clean branch to ensure removed files don't persist
          gitw status
          rm -rf __pycache__ **/__pycache__ .doctrees **/.doctrees .buildinfo **/.buildinfo
          gitw add .
          gitw status
          gitw config --global user.name "${GITHUB_ACTOR}"
          gitw config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          gitw commit --allow-empty --message "Update docs to ${GITHUB_SHA} from ${GITHUB_REF}"
          gitw push
