name: Release

on:
  release:
    types: [published]


jobs:
  upload_release:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Build and upload to PyPI
        run: nox -s upload_release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  docs:
    name: Build and push docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # To fetch all refs
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install nox
        run: pip install nox
      - name: Build docs
        run: nox -s docs
      - name: Commit and push docs
        run: |
          mkdir /tmp/gh-pages
          cp -r docs/build/* /tmp/gh-pages
          git checkout gh-pages
          git rm -r .  # Clean branch
          cp -r /tmp/gh-pages/* .
          touch .nojekyll
          rm -rf __pycache__ **/__pycache__
          git add .
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit --allow-empty --message "Update docs to ${GITHUB_SHA} from ${GITHUB_REF}"
          git push
